### ISSUE TITLE
Defense test checklist

### ISSUE THREAD

**Issue by mizzao** [mizzao/bot.land#32]
- [ ] Reflect / shields (especially team activations) are correct
- [ ] Movement / patrol is correct
- [ ] Artillery sneaks are dealt with
